
INSERT INTO terminos (termino) values 
('API'),
('Abandono escolar'),
('Abaratar el despido'),
('Abdicación'),
('Aborto'),
('Abre tu wifi'),
('Abstención'),
('Abuso sexual'),
('Acampada'),
('Acceso a la cultura'),
('Accidente laboral'),
('Acción'),
('Acción directa'),
('Acoso laboral'),
('Acoso sexual'),
('Acta'),
('Activismo'),
('Acuerdo de mínimos'),
('Adiestramiento pasivo'),
('Aforamiento'),
('Agencia de calificación'),
('Agencia pública de calificación'),
('Agresión'),
('Agrupación de electores'),
('Alianza monstruosa'),
('Alquiler'),
('Alquiler social'),
('Alternativas libres'),
('Amnistía'),
('Amnistía fiscal'),
('Amor romántico'),
('Androcentrismo'),
('Anticomunismo'),
('Antimilitarismo'),
('Antirracismo'),
('Apartheid sanitario'),
('Apartidismo'),
('Apoliticismo'),
('Apostasía'),
('Apoyo mutuo'),
('Armamento'),
('Arte'),
('Asamblea'),
('Asamblea extraordinaria'),
('Asamblearismo'),
('Ascetismo'),
('Asindicalismo'),
('Asociación vecinal'),
('Astenia activista'),
('Ataque DDoS'),
('Ateneo'),
('Atentado a la autoridad'),
('Atestado policial'),
('Ateísmo'),
('Auditoría de la deuda'),
('Autodefensa'),
('Autodefensa civil'),
('Autodefensa laboral'),
('Autofinanciación'),
('Autogestión'),
('Autoorganización'),
('Autoproducción'),
('Autoridad'),
('Autoritarismo'),
('Bajar el salario'),
('Banca pública'),
('Banca ética'),
('Banco de alimentos'),
('Banco de tiempo'),
('Banco malo'),
('Bandera'),
('Baño público'),
('Beca'),
('Bienes comunes'),
('Biocombustible'),
('Bioconstrucción'),
('Biodiversidad'),
('Bipartidismo'),
('Bolsa de Madrid'),
('Bono (finanzas)'),
('Bookmarklet'),
('Brecha salarial'),
('Burbuja inmobiliaria'),
('CERA'),
('Cadena imperialista'),
('Cadena perpetua'),
('Caja de ahorros'),
('Caja de resistencia'),
('Capital'),
('Capitalismo de rostro humano'),
('Caridad'),
('Carta abierta'),
('Carta de la Tierra'),
('Censo electoral'),
('Censura'),
('Centro de Estancia Controlada de Extranjeros'),
('Centro de Internamiento de Extranjeros'),
('Centro de medios'),
('Centro social'),
('Chapas'),
('Ciencia'),
('Circunscripción electoral'),
('Cisgénero'),
('Ciudadanismo'),
('Ciudadanía'),
('Clase dominante'),
('Clase media'),
('Clicktivismo'),
('Club Bilderberg'),
('Cláusulas abusivas'),
('Cláusulas suelo'),
('Coacción'),
('Coaching'),
('Coches oficiales'),
('Coeficiente de caja'),
('Colonialismo'),
('Comedor social'),
('Comercio'),
('Comida de traje'),
('Comisión de la Verdad'),
('Community manager'),
('Compa'),
('Comunicación'),
('Comunicación social'),
('Comunicado'),
('Concentración no comunicada'),
('Conceptos'),
('Conciencia'),
('Conciencia de clase'),
('Condonación'),
('Confederalismo democrático'),
('Conflicto'),
('Conflicto laboral'),
('Confluencia'),
('Conformidad de grupo'),
('Conocimiento'),
('Conocimiento libre'),
('Consejo de administración'),
('Consenso'),
('Consenso de mínimos'),
('Consulta ciudadana'),
('Consumismo'),
('Consumo colaborativo'),
('Consumo ecológico'),
('Consumo responsable'),
('Contracultura'),
('Contrainformación'),
('Contrapoder'),
('Contrato basura'),
('Contrato único'),
('Control de internet'),
('Convocatoria'),
('Convocatoria local'),
('Cooperativa integral'),
('Coordinación'),
('Copyleft'),
('Corralito'),
('Corrupción'),
('Cortometraje'),
('Creación del dinero'),
('Creative Commons'),
('Crianza'),
('Criminalización de la protesta social'),
('Criptografía'),
('Crisis'),
('Crisis económica'),
('Crisis-Estafa española 2008-2014'),
('Crowdfunding'),
('Cuarto poder (concepto)'),
('Cultura hacker'),
('Cultura libre'),
('Cunero'),
('Código abierto'),
('D0x'),
('DNI electrónico en España'),
('Dación en pago'),
('Dato'),
('Datos abiertos'),
('Declaración'),
('Declaración Universal de los Derechos Humanos'),
('Decrecimiento'),
('Decreto ley'),
('Delito'),
('Democracia'),
('Democracia burguesa'),
('Democracia digital'),
('Democracia directa'),
('Democracia líquida'),
('Democracia participativa'),
('Democracia real'),
('Denuncia'),
('Dependencia'),
('Derecho Penal del Enemigo'),
('Derecho a la educación'),
('Derecho a la huelga'),
('Derecho a la libertad de expresión'),
('Derecho a la libertad personal'),
('Derecho a la vida'),
('Derecho a la vivienda'),
('Derecho al aborto'),
('Derecho al trabajo'),
('Derecho de acceso de grupos sociales significativos'),
('Derecho de autodeterminación'),
('Derecho de participación política'),
('Derecho de rebelión'),
('Derecho de reunión'),
('Derecho inalienable'),
('Derechos fundamentales'),
('Derechos humanos'),
('Desahucio'),
('Desalojo (Acampada)'),
('Desarrollo sostenible'),
('Descentralización'),
('Desempleo'),
('Desigualdad'),
('Desinformación'),
('Deslocalización'),
('Desobediencia'),
('Desobediencia civil'),
('Desobediencia civil pacífica'),
('Desobediencia económica'),
('Despensa solidaria'),
('Despido'),
('Despido improcedente'),
('Destrucción del planeta'),
('Detención'),
('Deuda'),
('Deuda pública'),
('Diccionario feminista'),
('Diccionario político'),
('Dignidad'),
('Disenso'),
('Dispersión'),
('Distopía'),
('Diversidad funcional'),
('Diócesis'),
('Documental'),
('Dominio público'),
('Droga'),
('Drone'),
('Déficit tarifario'),
('Ecoaldea'),
('Ecofeminismo'),
('Economía de resistencia'),
('Economía del bien común'),
('Economía social'),
('Economía solidaria'),
('Editorial'),
('Educación'),
('Efecto Gamonal'),
('Efecto invernadero'),
('Ejecución hipotecaria'),
('Ejecución hipotecaria extrajudicial'),
('El espejismo de la igualdad'),
('Emergencia habitacional'),
('Empleado público'),
('Empleo digno'),
('Empoderamiento'),
('Empresa'),
('Empresa de trabajo temporal'),
('Empresa pública'),
('Encuentro'),
('Escaños Provinciales'),
('Esclavitud'),
('Escuela libre'),
('Espacio liberado'),
('Espectro político'),
('Especulación'),
('Especulación inmobiliaria'),
('Estado'),
('Estado del bienestar'),
('Estado policial'),
('Estadística'),
('Euribor'),
('Evasión fiscal'),
('Exclusión social'),
('Expediente de Regulación Temporal de Empleo'),
('Expediente de regulación de empleo'),
('Explotación laboral'),
('Expropiación'),
('Externalización'),
('Extranjero'),
('Falacia'),
('Falsedad documental'),
('Familia'),
('Feminazi'),
('Feminicidio'),
('Fiesta de la democracia'),
('Filtraciones'),
('Financiación del estado'),
('Fondo Monetario Internacional'),
('Fondo buitre'),
('Fondo de Liquidez Autonómica'),
('Fondo de alto riesgo'),
('Fondo de capital de riesgo'),
('Fondo de inversión'),
('Fracaso escolar'),
('Fraude de ley'),
('Fraude fiscal'),
('Frontera'),
('Fuerzas productivas'),
('Funcionariado'),
('Fundación'),
('Fórmula electoral'),
('GNU/Linux'),
('Gafas violetas'),
('Garantía hipotecaria'),
('Gasto militar'),
('Gasto social'),
('Gentrificación'),
('Germanocentrismo'),
('Gestión del entusiasmo'),
('Gobierno abierto'),
('Golpe de Estado'),
('Grupo de afinidad'),
('Grupo de consumo'),
('Grupo de trabajo'),
('Guerra'),
('Hacker'),
('Hacking'),
('Hacklab'),
('Hackmeeting'),
('Hacktivismo'),
('Hambre'),
('Hashtag'),
('Hegemonía'),
('Hembrismo'),
('Hipoteca'),
('Hombres de negro'),
('Homofobia'),
('Horizontalidad'),
('Huelga General Indefinida'),
('Huelga de celo'),
('IBEX 35'),
('ICE'),
('IRPF'),
('IRPH'),
('IVA'),
('Identificación'),
('Ideología'),
('Igualdad'),
('Igualdad ante la ley'),
('Igualitarismo'),
('Impuesto'),
('Impunidad'),
('Inclusividad'),
('Indefensión aprendida'),
('Independentismo'),
('Infancia'),
('Información'),
('Information literacy'),
('Ingeniería financiera'),
('Iniciativa legislativa popular en España'),
('Inmobiliaria'),
('Institución'),
('Inteligencia colectiva'),
('Interbarrios'),
('Intereses de demora'),
('Internet'),
('Intervención social'),
('Intimidad'),
('Inviolabilidad del domicilio'),
('Invisibilización'),
('Jubilación'),
('Justicia gratuita'),
('Kernel'),
('La Casta'),
('La Lista de Cifu'),
('Laicismo'),
('Lechera'),
('Legislación electoral española'),
('Ley electoral'),
('Lenguaje inclusivo'),
('Lenguaje no sexista'),
('Ley'),
('Ley Orgánica'),
('Ley dHondt'),
('Ley de segunda oportunidad'),
('Libertad'),
('Libertad de asociación'),
('Libertad de circulación y residencia'),
('Libertad de pensamiento'),
('Libertad de sindicación'),
('Libertad ideológica y religiosa'),
('Libertad política'),
('Libor'),
('Libre información'),
('Libros libres'),
('Licencia libre'),
('Lista de instituciones'),
('Listas de espera'),
('Literatura'),
('Lobby'),
('Lucha de clases'),
('Líder'),
('Machirulo'),
('Machismo'),
('Malnutrición infantil'),
('Maltrato'),
('Manifestación ilícita'),
('Manipulación mediática'),
('Mansplaining'),
('Marca España'),
('Mayoría absoluta'),
('Mayoría simple'),
('Medicamentazo'),
('Medio de contacto'),
('Medios de producción'),
('Megaminería'),
('Meme'),
('Memoria histórica'),
('Mente colmena'),
('Mercadillo de trueque'),
('Mercancía'),
('Mercantilización'),
('Metodología asamblearia'),
('Microblogging'),
('Micromachismo'),
('Miedo'),
('Migración'),
('Moneda social'),
('Movimiento okupa'),
('Movimiento social'),
('Municipalismo'),
('Mutua'),
('N-1 (Concepto)'),
('Nacionalización'),
('Nepotismo'),
('Netiqueta'),
('No violencia'),
('Nodo'),
('Normas de Basilea'),
('Noticia'),
('Nueva política'),
('ONG'),
('Objeción de conciencia'),
('Objeción fiscal'),
('Obra social'),
('Obsolescencia programada'),
('Oligarquía'),
('Opinión pública'),
('Organismo genéticamente modificado'),
('Organización'),
('P2P'),
('PAD'),
('PIB'),
('PIGS'),
('PPSOE'),
('PYMEs'),
('Pacto entre PP y PSOE'),
('Pancarta'),
('Paraíso fiscal'),
('Parlamento'),
('Parlamento autonómico'),
('Participaciones preferentes'),
('Participación'),
('Partido atrapalotodo'),
('Partido político'),
('Patriarcado'),
('Patronal'),
('País'),
('Peaje de respaldo'),
('Pedagogía antiautoritaria'),
('Película'),
('Pensamiento crítico'),
('Pensamiento único'),
('Pensión'),
('Pensión vitalicia'),
('Periodismo'),
('Periodismo de datos'),
('Periodismo de investigación'),
('Periódico'),
('Personas sin hogar'),
('Petición online de firmas'),
('Plaza'),
('Pobreza'),
('Pobreza energética'),
('Pobreza infantil'),
('Poder ciudadano'),
('Poder fáctico'),
('Poder popular'),
('Poderes supranacionales'),
('Politikverdrossenheit'),
('Populismo'),
('Precariado'),
('Precariedad'),
('Precio del transporte público'),
('Prensateniente'),
('Prescripción'),
('Presunción de inocencia'),
('Presunción de veracidad'),
('Presupuestos Generales del Estado'),
('Prima de riesgo'),
('Privatización'),
('Privilegio'),
('Procedimiento administrativo sancionador'),
('Procedimientos libres'),
('Proceso constituyente'),
('Procomún'),
('Proletariado'),
('Propaganda'),
('Propiedad'),
('Prosumidor'),
('Publicidad'),
('Publicidad machista'),
('Puerta giratoria'),
('Página web'),
('Queer'),
('Quincemayista'),
('RSS'),
('Racismo'),
('Radio libre'),
('Rating'),
('Reaccionario'),
('Rebelión'),
('Recorte'),
('Recuperación económica'),
('Recursos naturales'),
('Red de derechos sociales'),
('Red de solidaridad'),
('Red social'),
('Redada racista'),
('Reducción voluntaria de jornada'),
('Referéndum'),
('Reforma constitucional'),
('Reforma laboral'),
('Refundar el capitalismo'),
('Renta Mínima de Inserción'),
('Renta básica'),
('Repago'),
('Represión digital'),
('Represión policial'),
('Rescate'),
('Resistencia a la autoridad'),
('Resistencia pasiva'),
('Retransición'),
('Reunión no autorizada'),
('Reutilización'),
('Revocatoria del mandato'),
('Revolución'),
('Revolución política'),
('Rueda de prensa sin preguntas'),
('Régimen electoral'),
('SICAV'),
('Sacerdotes obreros'),
('Salario'),
('Salario mínimo interprofesional'),
('Seguro ético'),
('Semilla'),
('Separación de poderes'),
('Servicio público'),
('Sesgo cognitivo'),
('Sexismo'),
('Signos asamblearios'),
('Silencio mediático'),
('Sindicato'),
('Sindicato de ramo'),
('Sindicatos mayoritarios'),
('Sistema'),
('Sistema D’Hondt'),
('Sistema de red'),
('Sistema electoral'),
('Sitemap'),
('Soberanía'),
('Soberanía alimentaria'),
('Soberanía energética'),
('Sociedad de la información'),
('Socimi'),
('Socorro Rojo'),
('Software libre'),
('Solar (espacio)'),
('Solidaridad'),
('Sororidad'),
('Student loan'),
('Subasta judicial'),
('Subcontratación'),
('Superestructura'),
('Síndrome de Alienación Parental'),
('Síndrome de Sherwood'),
('TAE'),
('Taller de explotación laboral'),
('Tasa rosa'),
('Tasas a las transacciones financieras'),
('Tasas universitarias'),
('Tauromaquia'),
('Techo de cristal'),
('Tecnopolítica'),
('Televisión pública'),
('Teología'),
('Tercera República Española'),
('Terrateniente'),
('Terrorismo'),
('Terrorismo de Estado'),
('Terrorismo financiero'),
('Terrorismo machista'),
('Terrorismo patronal'),
('Test de Bechdel'),
('Teísmo'),
('Think tank'),
('Tortura'),
('Trabajador autónomo'),
('Trabajo digno'),
('Trabajo en red'),
('Tragedia de los comunes'),
('Transexual'),
('Transparencia'),
('Transterrados'),
('Transtierro'),
('Transversal'),
('Tratado'),
('Trending Topic'),
('Troika'),
('Turnismo'),
('Turno de oficio'),
('Tutorial'),
('Umbral de exclusión'),
('Umbral de la pobreza'),
('Unión Temporal de Empresas'),
('Urbanismo'),
('Utopía'),
('Valor de tasación'),
('Vigilancia estatal'),
('Violación'),
('Violencia'),
('Violencia de género'),
('Violencia machista'),
('Vivienda de protección oficial'),
('Vivienda digna'),
('Vivienda protegida'),
('Voluntad popular'),
('Voto'),
('Voto rogado'),
('Web semántica'),
('Wiki'),
('Wikidemocracia'),
('Wikigobierno'),
('Wikilegislación'),
('Xenofobia'),
('Yoga'),
('Zona temporalmente autónoma'),
('Ácrata');



DECLARE @cnt INT = 0;

WHILE @cnt < 10000
BEGIN

insert into indices (id_termino,nivel_confianza,descripcion,url) values (
(SELECT CAST(RAND() * 640 + 1 as INT)),
(SELECT CAST(RAND() * 99 + 1 as INT)),
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat felis enim, nec dictum mi dictum quis. Donec feugiat auctor nisi sit amet eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
'https://www.google.com.co'
)

   SET @cnt = @cnt + 1;
END;